# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
