# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xueli', models.CharField(max_length=10)),
                ('yuanxiao', models.CharField(max_length=20)),
                ('jiguan', models.CharField(max_length=20)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myhome.VipUser')),
            ],
        ),
    ]
