# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-17 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=77)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(choices=[(1, '男'), (0, '女')], max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('pic_url', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
