# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('store', models.IntegerField()),
                ('info', models.TextField()),
                ('pic_url', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('clicknum', models.IntegerField(default=0)),
                ('ordernum', models.IntegerField(default=0)),
                ('addtime', models.TimeField(auto_now_add=True)),
                ('cateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Cates')),
            ],
        ),
    ]
